name: voice_isolate_env
channels:
  - defaults
dependencies:
  - aom=3.6.0=h313beb8_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.3=h982b769_0
  - ffmpeg=6.1.1=h7693a39_3
  - filelock=3.20.0=py311hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - fsspec=2025.10.0=py311h7eb115d_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.84.4=h863a760_0
  - glib-tools=2.84.4=hff4a405_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py311h5c1b81f_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - importlib-metadata=8.5.0=py311hca03da5_0
  - jinja2=3.1.6=py311hca03da5_0
  - jpeg=9f=h2f69dba_0
  - lame=3.100=h1a28f6b_0
  - lcms2=2.16=he26ebf3_1
  - leptonica=1.82.0=hdedf53e_3
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libarchive=3.8.2=ha845c4f_0
  - libavif=1.1.1=h80987f9_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=5.29.3=h14f15fd_1
  - librsvg=2.56.3=h38920c8_2
  - libtheora=1.1.1=h1a28f6b_3
  - libtiff=4.7.0=h91aec0a_0
  - libtorch=2.5.1=gpu_mps_h7b1bc93_204
  - libuv=1.48.0=h80987f9_0
  - libvorbis=1.3.7=h1a28f6b_0
  - libvpx=1.13.1=h313beb8_0
  - libwebp=1.3.2=hf40cdb4_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py311h80987f9_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py311hca03da5_0
  - ncurses=6.5=hee39554_0
  - networkx=3.5=py311hca03da5_0
  - nomkl=3.0=0
  - numpy=2.3.4=py311h4bb6f22_1
  - numpy-base=2.3.4=py311h23175f9_1
  - openh264=2.1.1=h98b2900_0
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.0.18=h9b4081a_0
  - opentelemetry-api=1.37.0=py311hca03da5_0
  - pango=1.50.7=hf2328af_2
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.0.0=py311he2d6fe4_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - python=3.11.14=hf701271_0
  - pytorch=2.5.1=gpu_mps_py311hbd1d365_204
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.51.0=hab6afd1_0
  - sympy=1.14.0=py311hca03da5_0
  - tesseract=5.2.0=h9e66425_3
  - tk=8.6.15=hcd8a7d5_0
  - torchaudio=2.5.1=py311h7aedaa7_0
  - torchvision=0.20.1=mps_py311h620d032_102
  - typing-extensions=4.15.0=py311hca03da5_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zipp=3.21.0=py311hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /Users/marcusbluestone/opt/anaconda3/envs/voice_isolate_env
